//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.225
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZLERP.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZLERP.Resources.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 验证码 的本地化字符串。
        /// </summary>
        public static string Account_LogOn_CaptchaCode {
            get {
                return ResourceManager.GetString("Account_LogOn_CaptchaCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证码不正确 的本地化字符串。
        /// </summary>
        public static string Account_LogOn_CaptchaCodeIncorrect {
            get {
                return ResourceManager.GetString("Account_LogOn_CaptchaCodeIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录失败 的本地化字符串。
        /// </summary>
        public static string Account_LogOn_Failed {
            get {
                return ResourceManager.GetString("Account_LogOn_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不允许在此IP地址登录 的本地化字符串。
        /// </summary>
        public static string Account_LogOn_IPNotAllowed {
            get {
                return ResourceManager.GetString("Account_LogOn_IPNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密　码 的本地化字符串。
        /// </summary>
        public static string Account_LogOn_Password {
            get {
                return ResourceManager.GetString("Account_LogOn_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录密码错误 的本地化字符串。
        /// </summary>
        public static string Account_LogOn_PasswordIncorrect {
            get {
                return ResourceManager.GetString("Account_LogOn_PasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记住我 的本地化字符串。
        /// </summary>
        public static string Account_LogOn_RememberMe {
            get {
                return ResourceManager.GetString("Account_LogOn_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户已被锁定 的本地化字符串。
        /// </summary>
        public static string Account_LogOn_UserIsLocked {
            get {
                return ResourceManager.GetString("Account_LogOn_UserIsLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名 的本地化字符串。
        /// </summary>
        public static string Account_LogOn_UserName {
            get {
                return ResourceManager.GetString("Account_LogOn_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有该用户 的本地化字符串。
        /// </summary>
        public static string Account_LogOn_UserNotFound {
            get {
                return ResourceManager.GetString("Account_LogOn_UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 附件文件删除失败 的本地化字符串。
        /// </summary>
        public static string Attachment_Error_DeleteFileFailed {
            get {
                return ResourceManager.GetString("Attachment_Error_DeleteFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择车号 的本地化字符串。
        /// </summary>
        public static string Car_SelectCar {
            get {
                return ResourceManager.GetString("Car_SelectCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法删除，请先删除对应的子表数据 的本地化字符串。
        /// </summary>
        public static string ColumnReference {
            get {
                return ResourceManager.GetString("ColumnReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已存在相同的合同名称，请在原有合同上增加合同明细 的本地化字符串。
        /// </summary>
        public static string Contract_ContractName_Exists {
            get {
                return ResourceManager.GetString("Contract_ContractName_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 方 的本地化字符串。
        /// </summary>
        public static string Cube_Unit {
            get {
                return ResourceManager.GetString("Cube_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字典 的本地化字符串。
        /// </summary>
        public static string Entity_Dic {
            get {
                return ResourceManager.GetString("Entity_Dic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 浇筑方式 的本地化字符串。
        /// </summary>
        public static string Entity_Property_CastMode {
            get {
                return ResourceManager.GetString("Entity_Property_CastMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 施工部位 的本地化字符串。
        /// </summary>
        public static string Entity_Property_ConsPos {
            get {
                return ResourceManager.GetString("Entity_Property_ConsPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 砼强度 的本地化字符串。
        /// </summary>
        public static string Entity_Property_ConStrength {
            get {
                return ResourceManager.GetString("Entity_Property_ConStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合同名称 的本地化字符串。
        /// </summary>
        public static string Entity_Property_ContractName {
            get {
                return ResourceManager.GetString("Entity_Property_ContractName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户名称 的本地化字符串。
        /// </summary>
        public static string Entity_Property_CustName {
            get {
                return ResourceManager.GetString("Entity_Property_CustName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流水号 的本地化字符串。
        /// </summary>
        public static string Entity_Property_ID {
            get {
                return ResourceManager.GetString("Entity_Property_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 采购合同名称 的本地化字符串。
        /// </summary>
        public static string Entity_Property_StockPactName {
            get {
                return ResourceManager.GetString("Entity_Property_StockPactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 采购合同编号 的本地化字符串。
        /// </summary>
        public static string Entity_Property_StockPactNo {
            get {
                return ResourceManager.GetString("Entity_Property_StockPactNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原料名称 的本地化字符串。
        /// </summary>
        public static string Entity_Property_StuffName {
            get {
                return ResourceManager.GetString("Entity_Property_StuffName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统全局配置 的本地化字符串。
        /// </summary>
        public static string Entity_SysConfig {
            get {
                return ResourceManager.GetString("Entity_SysConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不允许上传的文件类型 的本地化字符串。
        /// </summary>
        public static string Error_FileTypeNotAllowed {
            get {
                return ResourceManager.GetString("Error_FileTypeNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您没有权限使用该功能 的本地化字符串。
        /// </summary>
        public static string Error_NotAuthorized {
            get {
                return ResourceManager.GetString("Error_NotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改数据大于限定区间 的本地化字符串。
        /// </summary>
        public static string Error_OverRange {
            get {
                return ResourceManager.GetString("Error_OverRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未提供必要的参数 的本地化字符串。
        /// </summary>
        public static string Error_ParameterRequired {
            get {
                return ResourceManager.GetString("Error_ParameterRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务单不存在 的本地化字符串。
        /// </summary>
        public static string Error_TaskNotExist {
            get {
                return ResourceManager.GetString("Error_TaskNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证失败 的本地化字符串。
        /// </summary>
        public static string Error_Validate_Failed {
            get {
                return ResourceManager.GetString("Error_Validate_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 yyyy年M月d日 的本地化字符串。
        /// </summary>
        public static string Format_Date_String {
            get {
                return ResourceManager.GetString("Format_Date_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 yyyy年M月d日 H:mm:ss 的本地化字符串。
        /// </summary>
        public static string Format_DateTime_String {
            get {
                return ResourceManager.GetString("Format_DateTime_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中联重科智慧商砼ERP 的本地化字符串。
        /// </summary>
        public static string Global_ProductName {
            get {
                return ResourceManager.GetString("Global_ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记录已经存在，请不要重复添加 的本地化字符串。
        /// </summary>
        public static string IsExistRecord {
            get {
                return ResourceManager.GetString("IsExistRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您的{0}许可将在&lt;b&gt;{1}&lt;/b&gt;天后过期，为了不影响您正常使用ERP系统，请尽快更新您的授权许可！如有疑问，请联系中联重科：0731-89751796 的本地化字符串。
        /// </summary>
        public static string License_Expire_CountDown {
            get {
                return ResourceManager.GetString("License_Expire_CountDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 受合同起止时间限制 的本地化字符串。
        /// </summary>
        public static string Limit_ContractTime {
            get {
                return ResourceManager.GetString("Limit_ContractTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 受垫资方量限制 的本地化字符串。
        /// </summary>
        public static string Limit_MatCube {
            get {
                return ResourceManager.GetString("Limit_MatCube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不受限制 的本地化字符串。
        /// </summary>
        public static string Limit_None {
            get {
                return ResourceManager.GetString("Limit_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 受预付方量限制 的本地化字符串。
        /// </summary>
        public static string Limit_PrepayCube {
            get {
                return ResourceManager.GetString("Limit_PrepayCube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该任务单的合同已被锁定&lt;br&gt;合同编号为： 的本地化字符串。
        /// </summary>
        public static string Msg_ContractIsLimited {
            get {
                return ResourceManager.GetString("Msg_ContractIsLimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该合同未审核或审核未通过 的本地化字符串。
        /// </summary>
        public static string Msg_ContractNotAudit {
            get {
                return ResourceManager.GetString("Msg_ContractNotAudit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该任务单的合同为非进行中的合同，不允许供货！&lt;br&gt;合同编号为： 的本地化字符串。
        /// </summary>
        public static string Msg_ContractStatus {
            get {
                return ResourceManager.GetString("Msg_ContractStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 试验按《普通混凝土外加剂均质性试验方法》GB/T8077-2000标准进行 的本地化字符串。
        /// </summary>
        public static string Msg_ExamGistForADM {
            get {
                return ResourceManager.GetString("Msg_ExamGistForADM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GB/T1596-2004 的本地化字符串。
        /// </summary>
        public static string Msg_ExamGistForAIR1 {
            get {
                return ResourceManager.GetString("Msg_ExamGistForAIR1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GB/T18046-2008 的本地化字符串。
        /// </summary>
        public static string Msg_ExamGistForAIR2 {
            get {
                return ResourceManager.GetString("Msg_ExamGistForAIR2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 JGJ52-2006 的本地化字符串。
        /// </summary>
        public static string Msg_ExamGistForCA {
            get {
                return ResourceManager.GetString("Msg_ExamGistForCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GB/T17671-1999 GB/T1346-2001 的本地化字符串。
        /// </summary>
        public static string Msg_ExamGistForCE {
            get {
                return ResourceManager.GetString("Msg_ExamGistForCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 JGJ52—2006 的本地化字符串。
        /// </summary>
        public static string Msg_ExamGistForFA {
            get {
                return ResourceManager.GetString("Msg_ExamGistForFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该批粉煤灰依据GB/T1596-2005标准，所检项目合格. 的本地化字符串。
        /// </summary>
        public static string Msg_ExamResultForAIR1 {
            get {
                return ResourceManager.GetString("Msg_ExamResultForAIR1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该批粒化高炉矿渣粉依据GB/T18046-2008检验评定，所检项目合格 的本地化字符串。
        /// </summary>
        public static string Msg_ExamResultForAIR2 {
            get {
                return ResourceManager.GetString("Msg_ExamResultForAIR2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该批石子依据JGJ52-2006标准，所检项目合格。 的本地化字符串。
        /// </summary>
        public static string Msg_ExamResultForCA {
            get {
                return ResourceManager.GetString("Msg_ExamResultForCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 样品经检测，所检各项性能指标都符合现行国家标准《通用硅酸盐水泥》GB175-2007规定的技术要求。 的本地化字符串。
        /// </summary>
        public static string Msg_ExamResultForCe {
            get {
                return ResourceManager.GetString("Msg_ExamResultForCe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该批砂子依据JGJ52—2006评定，所检项目合格 的本地化字符串。
        /// </summary>
        public static string Msg_ExamResultForFA {
            get {
                return ResourceManager.GetString("Msg_ExamResultForFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件不存在 的本地化字符串。
        /// </summary>
        public static string Msg_File_NotExist {
            get {
                return ResourceManager.GetString("Msg_File_NotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存在未处理的自动转退料记录 的本地化字符串。
        /// </summary>
        public static string Msg_hasAutoTz {
            get {
                return ResourceManager.GetString("Msg_hasAutoTz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该任务单的合同已过期&lt;br&gt;合同编号为： 的本地化字符串。
        /// </summary>
        public static string Msg_LimitContractTime {
            get {
                return ResourceManager.GetString("Msg_LimitContractTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该任务单的合同受垫资方量限制，已经不能再供货了，已超出 的本地化字符串。
        /// </summary>
        public static string Msg_LimitMatCube {
            get {
                return ResourceManager.GetString("Msg_LimitMatCube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该任务单的合同受预付方量限制，已经不能再供货了，已超出 的本地化字符串。
        /// </summary>
        public static string Msg_LimitPrepayCube {
            get {
                return ResourceManager.GetString("Msg_LimitPrepayCube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开盘鉴定失败 的本地化字符串。
        /// </summary>
        public static string Msg_OpenCheck_Failed {
            get {
                return ResourceManager.GetString("Msg_OpenCheck_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开盘鉴定完成，请前往试验管理-&gt;开盘鉴定查看并打印技术资料 的本地化字符串。
        /// </summary>
        public static string Msg_OpenCheck_Success {
            get {
                return ResourceManager.GetString("Msg_OpenCheck_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作失败 的本地化字符串。
        /// </summary>
        public static string Msg_Operate_Failed {
            get {
                return ResourceManager.GetString("Msg_Operate_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作成功 的本地化字符串。
        /// </summary>
        public static string Msg_Operate_Success {
            get {
                return ResourceManager.GetString("Msg_Operate_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信息发送失败 的本地化字符串。
        /// </summary>
        public static string Msg_Send_Fail {
            get {
                return ResourceManager.GetString("Msg_Send_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信息发送成功 的本地化字符串。
        /// </summary>
        public static string Msg_Send_Success {
            get {
                return ResourceManager.GetString("Msg_Send_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该任务单还没有发货记录，不能直接打印票据 的本地化字符串。
        /// </summary>
        public static string Msg_ShippingDoc_NotExist {
            get {
                return ResourceManager.GetString("Msg_ShippingDoc_NotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 两个桶仓所装的原料不相同，不允许更换桶仓 的本地化字符串。
        /// </summary>
        public static string Msg_Stuff_NoSame {
            get {
                return ResourceManager.GetString("Msg_Stuff_NoSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增 的本地化字符串。
        /// </summary>
        public static string Operation_Add {
            get {
                return ResourceManager.GetString("Operation_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string Operation_Delete {
            get {
                return ResourceManager.GetString("Operation_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        public static string Operation_Edit {
            get {
                return ResourceManager.GetString("Operation_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定的结算起止日期已存在结算单,结算日期范围不能交叉和重复! 的本地化字符串。
        /// </summary>
        public static string Settlement_Error_DateRangeDuplicate {
            get {
                return ResourceManager.GetString("Settlement_Error_DateRangeDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记录系统日志出错 的本地化字符串。
        /// </summary>
        public static string SysLog_Error_WriteLogError {
            get {
                return ResourceManager.GetString("SysLog_Error_WriteLogError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生产任务单 的本地化字符串。
        /// </summary>
        public static string TaskFormTitle {
            get {
                return ResourceManager.GetString("TaskFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 混凝土配比信息列表 的本地化字符串。
        /// </summary>
        public static string Title_BetonGrid {
            get {
                return ResourceManager.GetString("Title_BetonGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 施工配比信息列表 的本地化字符串。
        /// </summary>
        public static string Title_ConsGrid {
            get {
                return ResourceManager.GetString("Title_ConsGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 子表信息列表 的本地化字符串。
        /// </summary>
        public static string Title_ItemsGrid {
            get {
                return ResourceManager.GetString("Title_ItemsGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 砂浆配比信息列表 的本地化字符串。
        /// </summary>
        public static string Title_SlurryGrid {
            get {
                return ResourceManager.GetString("Title_SlurryGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生产任务信息列表 的本地化字符串。
        /// </summary>
        public static string Title_TaskGrid {
            get {
                return ResourceManager.GetString("Title_TaskGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 轮胎位置 的本地化字符串。
        /// </summary>
        public static string Tyre_InstallPlace {
            get {
                return ResourceManager.GetString("Tyre_InstallPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 轮胎型号 的本地化字符串。
        /// </summary>
        public static string Tyre_Model {
            get {
                return ResourceManager.GetString("Tyre_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 轮胎规格 的本地化字符串。
        /// </summary>
        public static string Tyre_Spec {
            get {
                return ResourceManager.GetString("Tyre_Spec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 轮胎类型 的本地化字符串。
        /// </summary>
        public static string Tyre_Type {
            get {
                return ResourceManager.GetString("Tyre_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该车对应的源运输单已经存在退转料记录，不能重复添加 的本地化字符串。
        /// </summary>
        public static string TZRelation_Error_HasTZRelationRecords {
            get {
                return ResourceManager.GetString("TZRelation_Error_HasTZRelationRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该车有未完成的退转料合车记录，不能重复添加 的本地化字符串。
        /// </summary>
        public static string TZRelation_Error_HasUnCompletedRecords {
            get {
                return ResourceManager.GetString("TZRelation_Error_HasUnCompletedRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该车有未完成的退转料记录，不能重复添加 的本地化字符串。
        /// </summary>
        public static string TZRelation_Error_HasUnCompletedRecords_NO {
            get {
                return ResourceManager.GetString("TZRelation_Error_HasUnCompletedRecords_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该车未找到退转料记录 的本地化字符串。
        /// </summary>
        public static string TZRelation_Error_HasUnCompletedRecords1 {
            get {
                return ResourceManager.GetString("TZRelation_Error_HasUnCompletedRecords1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入正确的Email格式\n示例：abc@123.com 的本地化字符串。
        /// </summary>
        public static string Validation_Email {
            get {
                return ResourceManager.GetString("Validation_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原始密码不正确 的本地化字符串。
        /// </summary>
        public static string Validation_OriginPasswordError {
            get {
                return ResourceManager.GetString("Validation_OriginPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该字段不能为空 的本地化字符串。
        /// </summary>
        public static string Validation_Required {
            get {
                return ResourceManager.GetString("Validation_Required", resourceCulture);
            }
        }
    }
}
