//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.225
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZLERP.Gps.GpsService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.vodofo.com/", ConfigurationName="GpsService.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.vodofo.com/getLoginKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getLoginKey(string strLoginName, string strPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.vodofo.com/Logout", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Logout(string strLoginKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.vodofo.com/getCurrentVehicleInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getCurrentVehicleInfo(string strLoginKey, string NumberPlateLists);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.vodofo.com/getLatestVehicleInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getLatestVehicleInfo(string strLoginKey, string strStartTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.vodofo.com/getVehicleSumInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getVehicleSumInfo(string strLoginKey, string NumberPlateLists, string strStartTime, string strEndTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.vodofo.com/getHistoryVehicleInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getHistoryVehicleInfo(string strLoginKey, string NumberPlateLists, string strStartTime, string strEndTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.vodofo.com/getObjectAddress", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getObjectAddress(string strLoginKey, string strVehicleNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.vodofo.com/getObjectAddressByDateTime", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getObjectAddressByDateTime(string strLoginKey, string strVehicleNum, System.DateTime dt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.vodofo.com/getCurrentRegion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getCurrentRegion(string strLoginKey, string NumberPlateLists);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.vodofo.com/getRegionByDateTime", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getRegionByDateTime(string strLoginKey, string NumberPlateLists, System.DateTime dt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.vodofo.com/sendMessage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int sendMessage(string strLoginKey, string NumberPlateLists, string strMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.vodofo.com/ABRange", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ABRange(string NumberPlateA, string NumberPlateB, int Meters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.vodofo.com/EMV_Add_Customer_Info", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int EMV_Add_Customer_Info(string LoginKey, string CustomerName, string Contacter, string TEL, string Address, string Remark);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.vodofo.com/EMV_Update_Customer_Info", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int EMV_Update_Customer_Info(string LoginKey, int CustomerID, string CustomerName, string Contacter, string TEL, string Address, string Remark);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.vodofo.com/EMV_Delete_Customer_Info", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int EMV_Delete_Customer_Info(string LoginKey, int CustomerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.vodofo.com/EMV_Get_Customer_Info", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet EMV_Get_Customer_Info(string LoginKey, string CustomerName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.vodofo.com/EMV_Add_Mixing_Station_Info", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int EMV_Add_Mixing_Station_Info(string LoginKey, string StationName, string Contacter, string TEL, string Address, string LoginName, string Password, double dMaxLng, double dMaxLat, double dMinLng, double dMinLat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.vodofo.com/EMV_Update_Mixing_Station_Info", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int EMV_Update_Mixing_Station_Info(string LoginKey, int StationID, string StationName, string Contacter, string TEL, string Address, double dMaxLng, double dMaxLat, double dMinLng, double dMinLat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.vodofo.com/EMV_Delete_Mixing_Station_Info", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int EMV_Delete_Mixing_Station_Info(string LoginKey, int StationID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.vodofo.com/EMV_Get_Mixing_Station_Info", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet EMV_Get_Mixing_Station_Info(string LoginKey, string StationName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.vodofo.com/EMV_Add_Construction_Site_Info", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int EMV_Add_Construction_Site_Info(string LoginKey, string CSName, string Address, int CustomerID, string Contactor, string TEL, string Remark, double dMaxLng, double dMaxLat, double dMinLng, double dMinLat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.vodofo.com/EMV_Update_Construction_Site_Info", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int EMV_Update_Construction_Site_Info(string LoginKey, int CSID, string CSName, string Address, int CustomerID, string Contactor, string TEL, string Remark, double dMaxLng, double dMaxLat, double dMinLng, double dMinLat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.vodofo.com/EMV_Delete_Construction_Site_Info", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int EMV_Delete_Construction_Site_Info(string LoginKey, int CSID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.vodofo.com/EMV_Get_Construction_Site_Info", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet EMV_Get_Construction_Site_Info(string LoginKey, string CSName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.vodofo.com/EMV_Add_Task_Info", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int EMV_Add_Task_Info(string LoginKey, string TaskCode, int CSID, int PartID, int BetonGradeID, int FeedingWay, int PlanAmount, string PlanTime, int iUnloadMinutes, int iReturnMinutes, string ScoutMan, int iStatus, string Remark);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.vodofo.com/EMV_Update_Task_Info", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int EMV_Update_Task_Info(string LoginKey, int TaskID, string TaskCode, int CSID, int PartID, int BetonGradeID, int FeedingWay, int PlanAmount, string PlanTime, int iUnloadMinutes, int iReturnMinutes, string ScoutMan, int iStatus, string Remark);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.vodofo.com/EMV_Delete_Task_Info", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int EMV_Delete_Task_Info(string LoginKey, int TaskID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.vodofo.com/EMV_Get_Task_Info", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet EMV_Get_Task_Info(string LoginKey, string TaskCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.vodofo.com/EMV_Add_Dispatch_Info", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int EMV_Add_Dispatch_Info(string LoginKey, string DispatchCode, string VehicleNum, string TaskID, double dFactAmount, string PlanLeaveTime, string Driver, int ShiftType, string Remark);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.vodofo.com/EMV_Update_Dispatch_Info", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int EMV_Update_Dispatch_Info(string LoginKey, int DispatchID, string DispatchCode, string VehicleNum, string TaskID, double dFactAmount, string PlanLeaveTime, string Driver, int ShiftType, string Remark);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.vodofo.com/EMV_Delete_Dispatch_Info", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int EMV_Delete_Dispatch_Info(string LoginKey, int DispatchID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.vodofo.com/EMV_Get_Dispatch_Info", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet EMV_Get_Dispatch_Info(string LoginKey, string DispatchCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.vodofo.com/EMV_Get_ProjectPart", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet EMV_Get_ProjectPart(string LoginKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.vodofo.com/EMV_Get_BetonGrade", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet EMV_Get_BetonGrade(string LoginKey);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : ZLERP.Gps.GpsService.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<ZLERP.Gps.GpsService.ServiceSoap>, ZLERP.Gps.GpsService.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getLoginKey(string strLoginName, string strPassword) {
            return base.Channel.getLoginKey(strLoginName, strPassword);
        }
        
        public bool Logout(string strLoginKey) {
            return base.Channel.Logout(strLoginKey);
        }
        
        public string getCurrentVehicleInfo(string strLoginKey, string NumberPlateLists) {
            return base.Channel.getCurrentVehicleInfo(strLoginKey, NumberPlateLists);
        }
        
        public string getLatestVehicleInfo(string strLoginKey, string strStartTime) {
            return base.Channel.getLatestVehicleInfo(strLoginKey, strStartTime);
        }
        
        public string getVehicleSumInfo(string strLoginKey, string NumberPlateLists, string strStartTime, string strEndTime) {
            return base.Channel.getVehicleSumInfo(strLoginKey, NumberPlateLists, strStartTime, strEndTime);
        }
        
        public string getHistoryVehicleInfo(string strLoginKey, string NumberPlateLists, string strStartTime, string strEndTime) {
            return base.Channel.getHistoryVehicleInfo(strLoginKey, NumberPlateLists, strStartTime, strEndTime);
        }
        
        public string getObjectAddress(string strLoginKey, string strVehicleNum) {
            return base.Channel.getObjectAddress(strLoginKey, strVehicleNum);
        }
        
        public string getObjectAddressByDateTime(string strLoginKey, string strVehicleNum, System.DateTime dt) {
            return base.Channel.getObjectAddressByDateTime(strLoginKey, strVehicleNum, dt);
        }
        
        public string getCurrentRegion(string strLoginKey, string NumberPlateLists) {
            return base.Channel.getCurrentRegion(strLoginKey, NumberPlateLists);
        }
        
        public string getRegionByDateTime(string strLoginKey, string NumberPlateLists, System.DateTime dt) {
            return base.Channel.getRegionByDateTime(strLoginKey, NumberPlateLists, dt);
        }
        
        public int sendMessage(string strLoginKey, string NumberPlateLists, string strMessage) {
            return base.Channel.sendMessage(strLoginKey, NumberPlateLists, strMessage);
        }
        
        public string ABRange(string NumberPlateA, string NumberPlateB, int Meters) {
            return base.Channel.ABRange(NumberPlateA, NumberPlateB, Meters);
        }
        
        public int EMV_Add_Customer_Info(string LoginKey, string CustomerName, string Contacter, string TEL, string Address, string Remark) {
            return base.Channel.EMV_Add_Customer_Info(LoginKey, CustomerName, Contacter, TEL, Address, Remark);
        }
        
        public int EMV_Update_Customer_Info(string LoginKey, int CustomerID, string CustomerName, string Contacter, string TEL, string Address, string Remark) {
            return base.Channel.EMV_Update_Customer_Info(LoginKey, CustomerID, CustomerName, Contacter, TEL, Address, Remark);
        }
        
        public int EMV_Delete_Customer_Info(string LoginKey, int CustomerID) {
            return base.Channel.EMV_Delete_Customer_Info(LoginKey, CustomerID);
        }
        
        public System.Data.DataSet EMV_Get_Customer_Info(string LoginKey, string CustomerName) {
            return base.Channel.EMV_Get_Customer_Info(LoginKey, CustomerName);
        }
        
        public int EMV_Add_Mixing_Station_Info(string LoginKey, string StationName, string Contacter, string TEL, string Address, string LoginName, string Password, double dMaxLng, double dMaxLat, double dMinLng, double dMinLat) {
            return base.Channel.EMV_Add_Mixing_Station_Info(LoginKey, StationName, Contacter, TEL, Address, LoginName, Password, dMaxLng, dMaxLat, dMinLng, dMinLat);
        }
        
        public int EMV_Update_Mixing_Station_Info(string LoginKey, int StationID, string StationName, string Contacter, string TEL, string Address, double dMaxLng, double dMaxLat, double dMinLng, double dMinLat) {
            return base.Channel.EMV_Update_Mixing_Station_Info(LoginKey, StationID, StationName, Contacter, TEL, Address, dMaxLng, dMaxLat, dMinLng, dMinLat);
        }
        
        public int EMV_Delete_Mixing_Station_Info(string LoginKey, int StationID) {
            return base.Channel.EMV_Delete_Mixing_Station_Info(LoginKey, StationID);
        }
        
        public System.Data.DataSet EMV_Get_Mixing_Station_Info(string LoginKey, string StationName) {
            return base.Channel.EMV_Get_Mixing_Station_Info(LoginKey, StationName);
        }
        
        public int EMV_Add_Construction_Site_Info(string LoginKey, string CSName, string Address, int CustomerID, string Contactor, string TEL, string Remark, double dMaxLng, double dMaxLat, double dMinLng, double dMinLat) {
            return base.Channel.EMV_Add_Construction_Site_Info(LoginKey, CSName, Address, CustomerID, Contactor, TEL, Remark, dMaxLng, dMaxLat, dMinLng, dMinLat);
        }
        
        public int EMV_Update_Construction_Site_Info(string LoginKey, int CSID, string CSName, string Address, int CustomerID, string Contactor, string TEL, string Remark, double dMaxLng, double dMaxLat, double dMinLng, double dMinLat) {
            return base.Channel.EMV_Update_Construction_Site_Info(LoginKey, CSID, CSName, Address, CustomerID, Contactor, TEL, Remark, dMaxLng, dMaxLat, dMinLng, dMinLat);
        }
        
        public int EMV_Delete_Construction_Site_Info(string LoginKey, int CSID) {
            return base.Channel.EMV_Delete_Construction_Site_Info(LoginKey, CSID);
        }
        
        public System.Data.DataSet EMV_Get_Construction_Site_Info(string LoginKey, string CSName) {
            return base.Channel.EMV_Get_Construction_Site_Info(LoginKey, CSName);
        }
        
        public int EMV_Add_Task_Info(string LoginKey, string TaskCode, int CSID, int PartID, int BetonGradeID, int FeedingWay, int PlanAmount, string PlanTime, int iUnloadMinutes, int iReturnMinutes, string ScoutMan, int iStatus, string Remark) {
            return base.Channel.EMV_Add_Task_Info(LoginKey, TaskCode, CSID, PartID, BetonGradeID, FeedingWay, PlanAmount, PlanTime, iUnloadMinutes, iReturnMinutes, ScoutMan, iStatus, Remark);
        }
        
        public int EMV_Update_Task_Info(string LoginKey, int TaskID, string TaskCode, int CSID, int PartID, int BetonGradeID, int FeedingWay, int PlanAmount, string PlanTime, int iUnloadMinutes, int iReturnMinutes, string ScoutMan, int iStatus, string Remark) {
            return base.Channel.EMV_Update_Task_Info(LoginKey, TaskID, TaskCode, CSID, PartID, BetonGradeID, FeedingWay, PlanAmount, PlanTime, iUnloadMinutes, iReturnMinutes, ScoutMan, iStatus, Remark);
        }
        
        public int EMV_Delete_Task_Info(string LoginKey, int TaskID) {
            return base.Channel.EMV_Delete_Task_Info(LoginKey, TaskID);
        }
        
        public System.Data.DataSet EMV_Get_Task_Info(string LoginKey, string TaskCode) {
            return base.Channel.EMV_Get_Task_Info(LoginKey, TaskCode);
        }
        
        public int EMV_Add_Dispatch_Info(string LoginKey, string DispatchCode, string VehicleNum, string TaskID, double dFactAmount, string PlanLeaveTime, string Driver, int ShiftType, string Remark) {
            return base.Channel.EMV_Add_Dispatch_Info(LoginKey, DispatchCode, VehicleNum, TaskID, dFactAmount, PlanLeaveTime, Driver, ShiftType, Remark);
        }
        
        public int EMV_Update_Dispatch_Info(string LoginKey, int DispatchID, string DispatchCode, string VehicleNum, string TaskID, double dFactAmount, string PlanLeaveTime, string Driver, int ShiftType, string Remark) {
            return base.Channel.EMV_Update_Dispatch_Info(LoginKey, DispatchID, DispatchCode, VehicleNum, TaskID, dFactAmount, PlanLeaveTime, Driver, ShiftType, Remark);
        }
        
        public int EMV_Delete_Dispatch_Info(string LoginKey, int DispatchID) {
            return base.Channel.EMV_Delete_Dispatch_Info(LoginKey, DispatchID);
        }
        
        public System.Data.DataSet EMV_Get_Dispatch_Info(string LoginKey, string DispatchCode) {
            return base.Channel.EMV_Get_Dispatch_Info(LoginKey, DispatchCode);
        }
        
        public System.Data.DataSet EMV_Get_ProjectPart(string LoginKey) {
            return base.Channel.EMV_Get_ProjectPart(LoginKey);
        }
        
        public System.Data.DataSet EMV_Get_BetonGrade(string LoginKey) {
            return base.Channel.EMV_Get_BetonGrade(LoginKey);
        }
    }
}
